services:
  frontend:
    build: .
    container_name: instagram_scraper_ui
    env_file:
      - .env
    expose:
      - "3000"
    ports:
      - "5173:3000"
    environment:
      - PORT=3000
    networks:
      - shared_net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  shared_net:
    external: true

